import Head from 'next/head'
import Image from 'next/image'
import MainBody from '../components/MainBody'
import NavBar from '../components/NavBar'
import styles from '../styles/Home.module.css'

export default function Home(data) {
  

  return (
    <div className={styles.container}>
      <Head>
        <title>Hello Coders</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>
      <MainBody data={data} />
    </div>
  )
}

export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`https://hellocoder.herokuapp.com/tutorials`)
  const data = await res.json()
  
  // Pass data to the page via props
  return { 
    props:
        { 
        data:data 
        } 
    }
}


